/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 6799e2c418e7de08ab1f72a65ea906e0734a1a5f */

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Linger_Framework_Controller___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_Linger_Framework_Controller__init arginfo_class_Linger_Framework_Controller___construct

#define arginfo_class_Linger_Framework_Controller_getRequest arginfo_class_Linger_Framework_Controller___construct

#define arginfo_class_Linger_Framework_Controller_getResponse arginfo_class_Linger_Framework_Controller___construct

#define arginfo_class_Linger_Framework_Controller_getView arginfo_class_Linger_Framework_Controller___construct
